services:
  postgres:
    image: postgres:16.1
    environment:
      # TODO: USE PASSWORDS!! REMOVE THIS LINE!!
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
  control:
    image: gpuctl-control
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8080:8080
    environment:
      GPU_DB_URL: postgres://postgres@postgres/postgres
    depends_on:
      postgres:
        condition: service_healthy
