[Server]
groundstation_port = 8080
webapi_port = 8000

[Database]
postgres = true
url = "postgres://postgres@postgres/postgres"
downsample_interval = "10m"

[Timeouts]
death_timeout = "60s"
monitor_interval = "60s"

[Auth]
username = "admin"
password = "password"

[Onboard]
datadir = "/data/gpuctl"
username = "dcg20"

[Onboard.Remote.Groundstation]
protocol = "https"
hostname = "gpuctl.perial.co.uk"
port = 443

[Onboard.Remote.Satellite]
data_interval = "15s"
heartbeat_interval = "5s"
fake_gpu = false

