name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  merge_group:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: 
          go-version: '1.21.x'
      - name: Build code
        run: go build ./...
      - name: Test code
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Test coverage check
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/gpuctl/gpuctl
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95
